DEBUG = False
ENV= 'development'
HOST = '0.0.0.0'
PORT = 6562
IOTA_NODE = ["https://nodes.thetangle.org:443"]
STORAGE_PATH = '_file/server'
SYMMETRIC = 'aes'
ASYMMETRIC = 'rsa'
HASH = 'sha256'
PING_TIMEOUT = 300
